let chartInstance = null;

document.addEventListener('DOMContentLoaded', () => {
    // driversData is injected by data.js generated by Swift!
    if (typeof driversData !== 'undefined' && driversData.length > 0) {
        initApp();
    } else {
        document.getElementById('driver-desc').innerText = "Error loading database. Please run the Swift app first.";
    }
});

function initApp() {
    const listContainer = document.getElementById('driver-list');
    listContainer.innerHTML = ''; // clear

    driversData.forEach((driver, index) => {
        const btn = document.createElement('button');
        btn.className = 'driver-btn';
        btn.innerText = driver.name;
        btn.onclick = () => selectDriver(index);
        listContainer.appendChild(btn);
    });

    // Select first driver by default
    selectDriver(0);
}

function selectDriver(index) {
    const driver = driversData[index];
    
    // Update active button styles
    document.querySelectorAll('.driver-btn').forEach((btn, i) => {
        if (i === index) {
            btn.classList.add('active');
            btn.style.backgroundColor = driver.teamColor;
            btn.style.borderColor = driver.teamColor;
        } else {
            btn.classList.remove('active');
            btn.style.backgroundColor = 'transparent';
            btn.style.borderColor = 'rgba(255,255,255,0.05)';
        }
    });

    // Update Theme CSS Variable
    document.documentElement.style.setProperty('--accent-color', driver.teamColor);

    // Apply Fade-in Animation
    const contentIds = ['driver-name', 'driver-team', 'driver-desc', 'stat-champ', 'stat-wins', 'stat-pods', 'stat-poles', 'driver-img'];
    contentIds.forEach(id => {
        const el = document.getElementById(id);
        el.classList.remove('fade-in');
        void el.offsetWidth; // trigger DOM reflow
        el.classList.add('fade-in');
    });

    // Update DOM Texts
    document.getElementById('driver-name').innerHTML = driver.name.replace(' ', '<br>');
    document.getElementById('driver-team').innerText = driver.team;
    document.getElementById('driver-desc').innerText = driver.description;
    
    // Update Image
    document.getElementById('driver-img').src = driver.imageFile;
    document.getElementById('driver-img').style.borderColor = driver.teamColor;
    
    document.getElementById('stat-champ').innerText = driver.championships;
    document.getElementById('stat-wins').innerText = driver.wins;
    document.getElementById('stat-pods').innerText = driver.podiums;
    document.getElementById('stat-poles').innerText = driver.polePositions;

    // Update Chart
    renderChart(driver);
}

function renderChart(driver) {
    const ctx = document.getElementById('performanceChart').getContext('2d');
    
    const labels = driver.yearlyStats.map(stat => stat.year);
    const dataPoints = driver.yearlyStats.map(stat => stat.points);

    if (chartInstance) {
        chartInstance.destroy();
    }

    // Convert HEX to RGBA for chart background area
    const hex = driver.teamColor.replace('#', '');
    const r = parseInt(hex.substring(0,2), 16);
    const g = parseInt(hex.substring(2,4), 16);
    const b = parseInt(hex.substring(4,6), 16);
    const bgColor = `rgba(${r}, ${g}, ${b}, 0.2)`;

    chartInstance = new Chart(ctx, {
        type: 'line',
        data: {
            labels: labels,
            datasets: [{
                label: 'Points',
                data: dataPoints,
                borderColor: driver.teamColor,
                backgroundColor: bgColor,
                borderWidth: 3,
                pointBackgroundColor: '#000',
                pointBorderColor: driver.teamColor,
                pointBorderWidth: 2,
                pointRadius: 6,
                pointHoverRadius: 8,
                fill: true,
                tension: 0.4
            }]
        },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            plugins: {
                legend: { display: false },
                tooltip: {
                    backgroundColor: 'rgba(0,0,0,0.8)',
                    titleFont: { family: 'Outfit', size: 14 },
                    bodyFont: { family: 'Outfit', size: 14 },
                    padding: 10,
                    displayColors: false
                }
            },
            scales: {
                y: {
                    grid: { color: 'rgba(255,255,255,0.05)' },
                    ticks: { color: '#888', font: { family: 'Outfit' } },
                    beginAtZero: true
                },
                x: {
                    grid: { color: 'rgba(255,255,255,0.05)' },
                    ticks: { color: '#888', font: { family: 'Outfit' } }
                }
            }
        }
    });
}
